NAME	=	ircserv

SRCS	=	./main.cpp \
			./client_query_parser.cpp \
			./build_replies.cpp \
			./build_server.cpp \
			./client_cmd_parser.cpp \
			./tmp_utils.cpp \
			./Commands/Away.cpp \
			./Commands/Cap.cpp \
			./Commands/Join.cpp \
			./Commands/Kick.cpp \
			./Commands/Kill.cpp \
			./Commands/List.cpp \
			./Commands/Mode.cpp \
			./Commands/Myhelp.cpp \
			./Commands/Names.cpp \
			./Commands/Nick.cpp \
			./Commands/Notice.cpp \
			./Commands/Oper.cpp \
			./Commands/Part.cpp \
			./Commands/Primsg.cpp \
			./Commands/Quit.cpp \
			./Commands/Topic.cpp \
			./Commands/User.cpp \
			./Commands/Who.cpp \
